### PR TITLE
Ability to provide channel to formatters.

### PR DESCRIPTION
**Pull request by rmikalkenas**

### CODE REVIEW

**Comment by gmponos** [comment]
IIRC a webhook can be for a specific channel.. This package can only be used with webhooks.. so does it make sense to pass the channel argument?

**Comment by gmponos** [comment]
please also rebase with master.

**Comment by rmikalkenas** [comment]
@gmponos its possible to use the same webhook url to push messages to different channels (on same workspace)

**Comment by gmponos** [comment]
Thank you.. will try to tag in the weekend.

**Pull request merged**
